<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 models/computer.glb -t -k -P -D
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { onMount } from 'svelte'
  import { Texture, MeshBasicMaterial } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      Computer_1: THREE.Mesh
      Computer_2: THREE.Mesh
      ComputerScreen_1: THREE.Mesh
      ComputerScreen_2: THREE.Mesh
      ComputerScreen_3: THREE.Mesh
      Keyboard: THREE.Mesh
    }
    materials: {
      Computer: THREE.MeshStandardMaterial
      Black: THREE.MeshStandardMaterial
      matGlass: THREE.MeshPhysicalMaterial
      matLight: THREE.MeshStandardMaterial
      matScreen: THREE.MeshStandardMaterial
      Keyboard: THREE.MeshStandardMaterial
    }
  }

  const load = () => useGltf<GLTFResult>('/models/computer.glb')
  const gltf = load()

  let screenTexture: Texture | null = null
  let screenMaterial: MeshBasicMaterial | null = null

  onMount(() => {
    screenTexture = new Texture()
    screenTexture.needsUpdate = true
    screenMaterial = new MeshBasicMaterial({ map: screenTexture })
  })
</script>

<T.Group dispose={false}>
  {#await gltf}
    <T.Mesh>
      <T.BoxGeometry args={[1, 1, 1]} />
      <T.MeshBasicMaterial color="gray" />
    </T.Mesh>
  {:then gltf}
    <T.Group
      name="Computer"
      position={[0, 0, 0]}
      scale={1}
    >
      <T.Mesh
        name="Computer_1"
        geometry={gltf.nodes.Computer_1.geometry}
        material={gltf.materials.Computer}
      />
      <T.Mesh
        name="Computer_2"
        geometry={gltf.nodes.Computer_2.geometry}
        material={gltf.materials.Black}
      />
    </T.Group>
    <T.Group
      name="ComputerScreen"
      position={[0, 0, 0]}
      scale={1}
    >
      <T.Mesh
        name="ComputerScreen_1"
        geometry={gltf.nodes.ComputerScreen_1.geometry}
        material={gltf.materials.matGlass}
      />
      <T.Mesh
        name="ComputerScreen_2"
        geometry={gltf.nodes.ComputerScreen_2.geometry}
        material={gltf.materials.matLight}
      />
      <T.Mesh
        name="ComputerScreen_3"
        geometry={gltf.nodes.ComputerScreen_3.geometry}
        material={screenMaterial ?? gltf.materials.matScreen}
      />
    </T.Group>
    <T.Mesh
      name="Keyboard"
      geometry={gltf.nodes.Keyboard.geometry}
      material={gltf.materials.Keyboard}
      scale={[1, 1, 1]}
    />
  {:catch err}
    <T.Mesh>
      <T.BoxGeometry args={[1, 1, 1]} />
      <T.MeshBasicMaterial color="red" />
    </T.Mesh>
  {/await}
</T.Group>
