<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 Computer.glb -t -k -D
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Computer_1: THREE.Mesh
      Computer_2: THREE.Mesh
      Period: THREE.Mesh
      asterisk: THREE.Mesh
      add: THREE.Mesh
      Comma: THREE.Mesh
      ['0']: THREE.Mesh
      ['1']: THREE.Mesh
      ['2']: THREE.Mesh
      ['3']: THREE.Mesh
      ['4']: THREE.Mesh
      ['5']: THREE.Mesh
      ['6']: THREE.Mesh
      ['7']: THREE.Mesh
      ['8']: THREE.Mesh
      ['9']: THREE.Mesh
      Equal: THREE.Mesh
      questionmark: THREE.Mesh
      at: THREE.Mesh
      BracketL: THREE.Mesh
      BracketR: THREE.Mesh
      A: THREE.Mesh
      B: THREE.Mesh
      Backslash: THREE.Mesh
      Backspace: THREE.Mesh
      C: THREE.Mesh
      Caps: THREE.Mesh
      Clear: THREE.Mesh
      Cursor: THREE.Mesh
      CursorAlt: THREE.Mesh
      D: THREE.Mesh
      Del: THREE.Mesh
      E: THREE.Mesh
      Escape: THREE.Mesh
      F: THREE.Mesh
      G: THREE.Mesh
      H: THREE.Mesh
      I: THREE.Mesh
      J: THREE.Mesh
      K: THREE.Mesh
      L: THREE.Mesh
      LeftShift: THREE.Mesh
      M: THREE.Mesh
      N: THREE.Mesh
      NumpadDecimal: THREE.Mesh
      Numpad0: THREE.Mesh
      Numpad1: THREE.Mesh
      Numpad2: THREE.Mesh
      Numpad3: THREE.Mesh
      Numpad4: THREE.Mesh
      Numpad5: THREE.Mesh
      Numpad6: THREE.Mesh
      Numpad7: THREE.Mesh
      Numpad8: THREE.Mesh
      Numpad9: THREE.Mesh
      O: THREE.Mesh
      Off: THREE.Mesh
      P: THREE.Mesh
      Q: THREE.Mesh
      R: THREE.Mesh
      Repeat: THREE.Mesh
      Return: THREE.Mesh
      RightShift: THREE.Mesh
      Run: THREE.Mesh
      S: THREE.Mesh
      ShiftLock: THREE.Mesh
      Spacebar: THREE.Mesh
      T: THREE.Mesh
      TAB: THREE.Mesh
      U: THREE.Mesh
      V: THREE.Mesh
      W: THREE.Mesh
      X: THREE.Mesh
      Y: THREE.Mesh
      Z: THREE.Mesh
      Screen: THREE.Mesh
      ScreenBacklight: THREE.Mesh
      ScreenGlass: THREE.Mesh
      NavBar: THREE.Mesh
    }
    materials: {
      Computer: THREE.MeshStandardMaterial
      Black: THREE.MeshStandardMaterial
      Keyboard: THREE.MeshStandardMaterial
      matScreen: THREE.MeshStandardMaterial
      matLight: THREE.MeshStandardMaterial
      matGlass: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('models/Computer.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...(props as any)}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Computer_1"
      geometry={gltf.nodes.Computer_1.geometry}
      material={gltf.materials.Computer}
    />
    <T.Mesh
      name="Computer_2"
      geometry={gltf.nodes.Computer_2.geometry}
      material={gltf.materials.Black}
    />
    <T.Mesh
      name="Period"
      geometry={gltf.nodes.Period.geometry}
      material={gltf.materials.Keyboard}
      position={[0.11, 0.28, 1.11]}
    />
    <T.Mesh
      name="asterisk"
      geometry={gltf.nodes.asterisk.geometry}
      material={gltf.materials.Keyboard}
      position={[0.15, 0.32, 0.86]}
    />
    <T.Mesh
      name="add"
      geometry={gltf.nodes.add.geometry}
      material={gltf.materials.Keyboard}
      position={[0.15, 0.29, 1.03]}
    />
    <T.Mesh
      name="Comma"
      geometry={gltf.nodes.Comma.geometry}
      material={gltf.materials.Keyboard}
      position={[0.03, 0.28, 1.11]}
    />
    <T.Mesh
      name="0"
      geometry={gltf.nodes['0'].geometry}
      material={gltf.materials.Keyboard}
      position={[0.06, 0.32, 0.86]}
    />
    <T.Mesh
      name="1"
      geometry={gltf.nodes['1'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.67, 0.32, 0.86]}
    />
    <T.Mesh
      name="2"
      geometry={gltf.nodes['2'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.59, 0.32, 0.86]}
    />
    <T.Mesh
      name="3"
      geometry={gltf.nodes['3'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.51, 0.32, 0.86]}
    />
    <T.Mesh
      name="4"
      geometry={gltf.nodes['4'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.43, 0.32, 0.86]}
    />
    <T.Mesh
      name="5"
      geometry={gltf.nodes['5'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.35, 0.32, 0.86]}
    />
    <T.Mesh
      name="6"
      geometry={gltf.nodes['6'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.26, 0.32, 0.86]}
    />
    <T.Mesh
      name="7"
      geometry={gltf.nodes['7'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.18, 0.32, 0.86]}
    />
    <T.Mesh
      name="8"
      geometry={gltf.nodes['8'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.1, 0.32, 0.86]}
    />
    <T.Mesh
      name="9"
      geometry={gltf.nodes['9'].geometry}
      material={gltf.materials.Keyboard}
      position={[-0.02, 0.32, 0.86]}
    />
    <T.Mesh
      name="Equal"
      geometry={gltf.nodes.Equal.geometry}
      material={gltf.materials.Keyboard}
      position={[0.23, 0.32, 0.86]}
    />
    <T.Mesh
      name="questionmark"
      geometry={gltf.nodes.questionmark.geometry}
      material={gltf.materials.Keyboard}
      position={[0.19, 0.28, 1.11]}
    />
    <T.Mesh
      name="at"
      geometry={gltf.nodes.at.geometry}
      material={gltf.materials.Keyboard}
      position={[0.24, 0.29, 1.03]}
    />
    <T.Mesh
      name="BracketL"
      geometry={gltf.nodes.BracketL.geometry}
      material={gltf.materials.Keyboard}
      position={[0.2, 0.31, 0.94]}
    />
    <T.Mesh
      name="BracketR"
      geometry={gltf.nodes.BracketR.geometry}
      material={gltf.materials.Keyboard}
      position={[0.32, 0.29, 1.03]}
    />
    <T.Mesh
      name="A"
      geometry={gltf.nodes.A.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.58, 0.29, 1.03]}
    />
    <T.Mesh
      name="B"
      geometry={gltf.nodes.B.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.21, 0.28, 1.11]}
    />
    <T.Mesh
      name="Backslash"
      geometry={gltf.nodes.Backslash.geometry}
      material={gltf.materials.Keyboard}
      position={[0.28, 0.31, 0.94]}
    />
    <T.Mesh
      name="Backspace"
      geometry={gltf.nodes.Backspace.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.75, 0.32, 0.86]}
    />
    <T.Mesh
      name="C"
      geometry={gltf.nodes.C.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.38, 0.28, 1.11]}
    />
    <T.Mesh
      name="Caps"
      geometry={gltf.nodes.Caps.geometry}
      material={gltf.materials.Keyboard}
      position={[0.31, 0.32, 0.86]}
    />
    <T.Mesh
      name="Clear"
      geometry={gltf.nodes.Clear.geometry}
      material={gltf.materials.Keyboard}
      position={[0.46, 0.28, 1.11]}
    />
    <T.Mesh
      name="Cursor"
      geometry={gltf.nodes.Cursor.geometry}
      material={gltf.materials.Keyboard}
      position={[0.39, 0.32, 0.86]}
    />
    <T.Mesh
      name="CursorAlt"
      geometry={gltf.nodes.CursorAlt.geometry}
      material={gltf.materials.Keyboard}
      position={[0.36, 0.31, 0.94]}
    />
    <T.Mesh
      name="D"
      geometry={gltf.nodes.D.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.42, 0.29, 1.03]}
    />
    <T.Mesh
      name="Del"
      geometry={gltf.nodes.Del.geometry}
      material={gltf.materials.Keyboard}
      position={[0.45, 0.31, 0.94]}
    />
    <T.Mesh
      name="E"
      geometry={gltf.nodes.E.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.45, 0.31, 0.94]}
    />
    <T.Mesh
      name="Escape"
      geometry={gltf.nodes.Escape.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.75, 0.29, 1.03]}
    />
    <T.Mesh
      name="F"
      geometry={gltf.nodes.F.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.34, 0.29, 1.03]}
    />
    <T.Mesh
      name="G"
      geometry={gltf.nodes.G.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.26, 0.29, 1.03]}
    />
    <T.Mesh
      name="H"
      geometry={gltf.nodes.H.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.17, 0.29, 1.03]}
    />
    <T.Mesh
      name="I"
      geometry={gltf.nodes.I.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.05, 0.31, 0.94]}
    />
    <T.Mesh
      name="J"
      geometry={gltf.nodes.J.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.09, 0.29, 1.03]}
    />
    <T.Mesh
      name="K"
      geometry={gltf.nodes.K.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.01, 0.29, 1.03]}
    />
    <T.Mesh
      name="L"
      geometry={gltf.nodes.L.geometry}
      material={gltf.materials.Keyboard}
      position={[0.07, 0.29, 1.03]}
    />
    <T.Mesh
      name="LeftShift"
      geometry={gltf.nodes.LeftShift.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.64, 0.28, 1.11]}
    />
    <T.Mesh
      name="M"
      geometry={gltf.nodes.M.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.05, 0.28, 1.11]}
    />
    <T.Mesh
      name="N"
      geometry={gltf.nodes.N.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.13, 0.28, 1.11]}
    />
    <T.Mesh
      name="NumpadDecimal"
      geometry={gltf.nodes.NumpadDecimal.geometry}
      material={gltf.materials.Keyboard}
      position={[0.79, 0.28, 1.11]}
    />
    <T.Mesh
      name="Numpad0"
      geometry={gltf.nodes.Numpad0.geometry}
      material={gltf.materials.Keyboard}
      position={[0.67, 0.28, 1.11]}
    />
    <T.Mesh
      name="Numpad1"
      geometry={gltf.nodes.Numpad1.geometry}
      material={gltf.materials.Keyboard}
      position={[0.62, 0.29, 1.03]}
    />
    <T.Mesh
      name="Numpad2"
      geometry={gltf.nodes.Numpad2.geometry}
      material={gltf.materials.Keyboard}
      position={[0.71, 0.29, 1.03]}
    />
    <T.Mesh
      name="Numpad3"
      geometry={gltf.nodes.Numpad3.geometry}
      material={gltf.materials.Keyboard}
      position={[0.79, 0.29, 1.03]}
    />
    <T.Mesh
      name="Numpad4"
      geometry={gltf.nodes.Numpad4.geometry}
      material={gltf.materials.Keyboard}
      position={[0.62, 0.31, 0.94]}
    />
    <T.Mesh
      name="Numpad5"
      geometry={gltf.nodes.Numpad5.geometry}
      material={gltf.materials.Keyboard}
      position={[0.71, 0.31, 0.94]}
    />
    <T.Mesh
      name="Numpad6"
      geometry={gltf.nodes.Numpad6.geometry}
      material={gltf.materials.Keyboard}
      position={[0.79, 0.31, 0.94]}
    />
    <T.Mesh
      name="Numpad7"
      geometry={gltf.nodes.Numpad7.geometry}
      material={gltf.materials.Keyboard}
      position={[0.62, 0.32, 0.86]}
    />
    <T.Mesh
      name="Numpad8"
      geometry={gltf.nodes.Numpad8.geometry}
      material={gltf.materials.Keyboard}
      position={[0.71, 0.32, 0.86]}
    />
    <T.Mesh
      name="Numpad9"
      geometry={gltf.nodes.Numpad9.geometry}
      material={gltf.materials.Keyboard}
      position={[0.79, 0.32, 0.86]}
    />
    <T.Mesh
      name="O"
      geometry={gltf.nodes.O.geometry}
      material={gltf.materials.Keyboard}
      position={[0.04, 0.31, 0.94]}
    />
    <T.Mesh
      name="Off"
      geometry={gltf.nodes.Off.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.73, 0.28, 1.11]}
    />
    <T.Mesh
      name="P"
      geometry={gltf.nodes.P.geometry}
      material={gltf.materials.Keyboard}
      position={[0.12, 0.31, 0.94]}
    />
    <T.Mesh
      name="Q"
      geometry={gltf.nodes.Q.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.62, 0.31, 0.94]}
    />
    <T.Mesh
      name="R"
      geometry={gltf.nodes.R.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.37, 0.31, 0.94]}
    />
    <T.Mesh
      name="Repeat"
      geometry={gltf.nodes.Repeat.geometry}
      material={gltf.materials.Keyboard}
      position={[0.38, 0.28, 1.11]}
    />
    <T.Mesh
      name="Return"
      geometry={gltf.nodes.Return.geometry}
      material={gltf.materials.Keyboard}
      position={[0.43, 0.29, 1.03]}
    />
    <T.Mesh
      name="RightShift"
      geometry={gltf.nodes.RightShift.geometry}
      material={gltf.materials.Keyboard}
      position={[0.29, 0.28, 1.11]}
    />
    <T.Mesh
      name="Run"
      geometry={gltf.nodes.Run.geometry}
      material={gltf.materials.Keyboard}
      position={[0.47, 0.32, 0.86]}
    />
    <T.Mesh
      name="S"
      geometry={gltf.nodes.S.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.5, 0.29, 1.03]}
    />
    <T.Mesh
      name="ShiftLock"
      geometry={gltf.nodes.ShiftLock.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.66, 0.29, 1.03]}
    />
    <T.Mesh
      name="Spacebar"
      geometry={gltf.nodes.Spacebar.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.18, 0.27, 1.19]}
    />
    <T.Mesh
      name="T"
      geometry={gltf.nodes.T.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.29, 0.31, 0.94]}
    />
    <T.Mesh
      name="TAB"
      geometry={gltf.nodes.TAB.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.73, 0.31, 0.94]}
    />
    <T.Mesh
      name="U"
      geometry={gltf.nodes.U.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.13, 0.31, 0.94]}
    />
    <T.Mesh
      name="V"
      geometry={gltf.nodes.V.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.3, 0.28, 1.11]}
    />
    <T.Mesh
      name="W"
      geometry={gltf.nodes.W.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.54, 0.31, 0.94]}
    />
    <T.Mesh
      name="X"
      geometry={gltf.nodes.X.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.46, 0.28, 1.11]}
    />
    <T.Mesh
      name="Y"
      geometry={gltf.nodes.Y.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.21, 0.31, 0.94]}
    />
    <T.Mesh
      name="Z"
      geometry={gltf.nodes.Z.geometry}
      material={gltf.materials.Keyboard}
      position={[-0.54, 0.28, 1.11]}
    />
    <T.Mesh
      name="Screen"
      geometry={gltf.nodes.Screen.geometry}
      material={gltf.materials.matScreen}
      on:create={({ ref }) => {
        console.log('Screen mesh created:', ref);
        console.log('Screen position:', ref.position);
        console.log('Screen geometry:', ref.geometry.boundingBox);
        // Force compute bounding box
        ref.geometry.computeBoundingBox();
        console.log('Screen bounding box:', ref.geometry.boundingBox);
      }}
    />
    {#if children}
      {@render children({ ref: ref! })}
    {/if}
    
    <T.Mesh
      name="ScreenBacklight"
      geometry={gltf.nodes.ScreenBacklight.geometry}
      material={gltf.materials.matLight}
    />
    
    <T.Mesh
      name="ScreenGlass"
      geometry={gltf.nodes.ScreenGlass.geometry}
      material={gltf.materials.matGlass}
      opacity={0}
    />
    
    <T.Mesh
      name="NavBar"
      geometry={gltf.nodes.NavBar.geometry}
      material={gltf.materials.matScreen}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}
</T.Group>
